inputs: D:\pyWorkSpace\test\PDF-Extract-Kit-main\inputs\ocr\开放式缴费平台产品推荐手册.pdf
outputs: logs/ocr_layout
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: D:\pyWorkSpace\test\PDF-Extract-Kit-main\models\Layout\YOLO\doclayout_yolo_ft.pt
      visualize: True