inputs: ../../inputs/prdt_doc_to_rec_md
outputs: ../../assets/doc_to_recommendation
tasks:
  ocr:
    visualize: True
    model: ocr_ppocr
    model_config:
      lang: ch
      show_log: True
      det_model_dir: models/OCR/PaddleOCR/det/ch_PP-OCRv4_det
      rec_model_dir: models/OCR/PaddleOCR/rec/ch_PP-OCRv4_rec
      det_db_box_thresh: 0.3
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: ../../models/Layout/YOLO/doclayout_yolo_docstructbench_imgsz1280_2501.pt
      visualize: True